name: My First CI Workflow
on: [push]
jobs:
  setup_and_test:
    name: Setup and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: run test
        run: npm test
